In [1]:
import pandas as pd
import wandb

wandb.login(key="cf344975eb80edf6f0d52af80528cc6094234caf")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /home/rahul/.netrc
wandb: Currently logged in as: rahul-e-dev to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [41]:
api = wandb.Api()
runs = api.runs("rahul-e-dev/evaluate_tba")
baseline_run_name = "pretty-dawn-59"
run = next(run for run in runs if run.name == baseline_run_name)
artifact_name = next(a for a in run.logged_artifacts() if "split_results" in a.name).name
artifact = api.artifact(f"rahul-e-dev/evaluate_tba/{artifact_name}")
wandb_table = artifact.get("split_results")
baseline_df = wandb_table.get_dataframe()

wandb:   1 of 1 files downloaded.

In [42]:
api = wandb.Api()
runs = api.runs("rahul-e-dev/evaluate_tba")
baseline_run_name = "fluent-brook-62"
run = next(run for run in runs if run.name == baseline_run_name)
artifact_name = next(a for a in run.logged_artifacts() if "split_results" in a.name).name
artifact = api.artifact(f"rahul-e-dev/evaluate_tba/{artifact_name}")
wandb_table = artifact.get("split_results")
deltaprop_df = wandb_table.get_dataframe()

wandb:   1 of 1 files downloaded.

In [49]:
baseline_df = pd.read_csv("./base.csv").drop("Unnamed: 0", axis=1)
deltaprop_df = pd.read_csv("./del.csv").drop("Unnamed: 0", axis=1)

In [50]:
baseline_df = baseline_df.set_index(['outer', 'inner'])
deltaprop_df = deltaprop_df.set_index(['outer', 'inner'])

# baseline_df['method'] = 'baseline'
# deltaprop_df['method'] = 'deltaprop'

In [51]:
baseline_df

             accuracy  balanced_accuracy        f1  precision    recall  \
outer inner
0     0      0.715385           0.715385  0.725926   0.700000  0.753846
      1      0.620155           0.619408  0.637037   0.623188  0.651515
1     0      0.669118           0.667869  0.693878   0.708333  0.680000
      1      0.656000           0.654378  0.715232   0.613636  0.857143
2     0      0.746269           0.741583  0.784810   0.696629  0.898551
      1      0.616000           0.615779  0.606557   0.606557  0.606557
3     0      0.614754           0.610753  0.692810   0.582418  0.854839
      1      0.717241           0.674342  0.568421   0.710526  0.473684
4     0      0.708333           0.708333  0.740741   0.666667  0.833333
      1      0.703704           0.699824  0.733333   0.696203  0.774648

              roc_auc  average_precision
outer inner
0     0      0.822722           0.841813
      1      0.769841           0.803254
1     0      0.754754           0.777375
      1      0.735535           0.688978
2     0      0.815385           0.788738
      1      0.713627           0.692137
3     0      0.746505           0.761674
      1      0.746212           0.679738
4     0      0.783889           0.772199
      1      0.774208           0.828219

In [52]:
deltaprop_df

             accuracy  balanced_accuracy        f1  precision    recall  \
outer inner
0     0      0.723077           0.723077  0.653846   0.871795  0.523077
      1      0.674419           0.678571  0.611111   0.785714  0.500000
1     0      0.720588           0.714536  0.753247   0.734177  0.773333
      1      0.704000           0.703149  0.733813   0.671053  0.809524
2     0      0.746269           0.745151  0.760563   0.739726  0.782609
      1      0.616000           0.624616  0.714286   0.560748  0.983607
3     0      0.688525           0.687097  0.716418   0.666667  0.774194
      1      0.668966           0.591308  0.351351   0.764706  0.228070
4     0      0.650000           0.650000  0.588235   0.714286  0.500000
      1      0.659259           0.649868  0.719512   0.634409  0.830986

              roc_auc  average_precision
outer inner
0     0      0.802604           0.827810
      1      0.797980           0.816243
1     0      0.748852           0.760698
      1      0.760113           0.732789
2     0      0.808250           0.788010
      1      0.756148           0.756107
3     0      0.752151           0.750209
      1      0.731459           0.658525
4     0      0.719444           0.663917
      1      0.756822           0.778074

In [53]:
diffs = deltaprop_df - baseline_df

In [54]:
for metric in diffs.columns:
    vals = diffs.loc[:, metric]
    variances = vals.groupby(level=0).var()
    fstat = (vals ** 2).sum() / (2 * variances.sum())
    print(metric, fstat, stats.f.sf(fstat, 10, 5))

accuracy 1.2222761176440828 0.43651335036316935
balanced_accuracy 0.9529383084860613 0.5587497622431079
f1 0.9459827296427703 0.5623713867768749
precision 3.657771265612529 0.08254052164996425
recall 0.9457129705649875 0.5625123325716297
roc_auc 1.0054090013641537 0.5322077664006093
average_precision 1.78254128561027 0.2718009074022467

In [55]:
diffs

             accuracy  balanced_accuracy        f1  precision    recall  \
outer inner
0     0      0.007692           0.007692 -0.072080   0.171795 -0.230769
      1      0.054264           0.059163 -0.025926   0.162526 -0.151515
1     0      0.051471           0.046667  0.059369   0.025844  0.093333
      1      0.048000           0.048771  0.018581   0.057416 -0.047619
2     0      0.000000           0.003567 -0.024247   0.043097 -0.115942
      1      0.000000           0.008837  0.107728  -0.045810  0.377049
3     0      0.073770           0.076344  0.023607   0.084249 -0.080645
      1     -0.048276          -0.083034 -0.217070   0.054180 -0.245614
4     0     -0.058333          -0.058333 -0.152505   0.047619 -0.333333
      1     -0.044444          -0.049956 -0.013821  -0.061794  0.056338

              roc_auc  average_precision
outer inner
0     0     -0.020118          -0.014003
      1      0.028139           0.012989
1     0     -0.005902          -0.016677
      1      0.024578           0.043810
2     0     -0.007135          -0.000727
      1      0.042520           0.063970
3     0      0.005645          -0.011465
      1     -0.014753          -0.021213
4     0     -0.064444          -0.108282
      1     -0.017386          -0.050145